config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :pranks, only:[:index, :show, :new, :create] do
    resources :bookings, only:[:new, :create]
  end
  resources :bookings, only:[:index, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :prank
  has_one_attached :photo

  def pending?
    status == 'pending'
  end

  def accepted?
    status == 'accepted'
  end

  def completed?
    status == 'completed'
  end
end

app/models/prank.rb
class Prank < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_one_attached :photo
  validates :name, presence: true
  validates :content, presence: true
  validates :price, presence: true
  validates :city, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_content_city, against: {
    name: 'A',
    content: 'B',
    city: 'C'
  },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pranks, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :pranks, source: :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_prank, only: [:new, :create]
  def index
    @bookings = policy_scope(Booking).where(user: current_user)
    @bookings_as_owner = policy_scope(Booking).where(prank: current_user.pranks)
  end

  def new
    set_prank
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    set_prank
    @booking.prank = @prank
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :bookings_path
    end
  end

  private

  def set_prank
    @prank = Prank.find(params[:prank_id])
  end

  def booking_params
    params.require(:booking).permit(:date, :description, :status, :prank_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/pranks_controller.rb
class PranksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @pranks =
    if params[:query]
      policy_scope(Prank).search_by_name_content_city(params[:query])
    else
      policy_scope(Prank)
    end
  end

  def show
    @booking = Booking.new
    @prank = Prank.find(params[:id])
    authorize @prank
  end

  def new
    @prank = Prank.new
    @prank.user = current_user
    authorize @prank
  end

  def create
    @prank = Prank.create(prank_params)
    @prank.user = current_user
    authorize @prank
    if @prank.save
      redirect_to prank_path(@prank)
    else
      render :new
    end
  end

  def prank_params
    params.require(:prank).permit(:name, :content, :price, :city, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container-booking d-flex flex-column align-items-center pt-5">
  <div class="card-booking d-flex flex-column align-items-center justify-content-center">
    <h1>Your Bookings</h1>
    <% if @bookings.empty? %>
      <p>There are no bookings yet</p>
    <% else %>
  </br></br>
        <h3>Pranks booked</h3>
        <% @bookings.each do |booking| %>
          <div class="card-product border border-dark" style="width: 600px">
            <%= booking.prank.photo.attached? ? cl_image_tag(booking.prank.photo.key) : cl_image_tag("https://res.cloudinary.com/dzwpbkn3u/image/upload/v1621747327/homeless-chic_n3ntvs.png") %>
            <div class="card-product-infos">
              <div class="w-100">
                <p><b><%= booking.prank.name %></b></p>
                <p><%= booking.date.strftime('%A, %b %d') %></p>
                <p><%= booking.description %></p>
                <p><%= booking.status.capitalize %></p>
              </div>
              <% if booking.completed? %>
                <div id="accordion">
                  <div class="card border-0">
                    <div id="headingOne">
                      <div class="mb-0">
                        <button class="btn btn-flat btn-block mt-1 text-decoration-none border-0" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                          See Result
                        </button>
                      </div>
                    </div>
                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                      <div class="card-body mb-0">
                        <%= booking.photo.attached? ? cl_image_tag(booking.photo.key, class: "w-100") : cl_image_tag("https://res.cloudinary.com/dzwpbkn3u/image/upload/v1621747327/homeless-chic_n3ntvs.png") %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <%= link_to 'All pranks', pranks_path, class: 'btn btn-flat mb-3 mt-3 w-10' %>
    </div>
    <% if current_user == @bookings_as_owner %>
    <div class="container-booking d-flex flex-column align-items-center">
      <% if @bookings_as_owner.present? %>
        <h3>Pranks to pull</h3>
        <% @bookings_as_owner.each do |booking| %>
          <% if current_user == booking.prank.user %>
            <div class="card-product border border-dark" style="width: 600px">
              <%= image_tag "https://res.cloudinary.com/dzwpbkn3u/image/upload/v1621747327/homeless-chic_n3ntvs.png" %>
              <div class="card-product-infos">
                <div>
                  <p><b><%= booking.prank.name %></b></p>
                  <p><%= booking.date.strftime('%A, %b %d') %></p>
                  <p><%= booking.description %></p>
                </div>
                <div class="card-product-actions d-flex flex-row justify-content-center">
                  <% if booking.pending? %>
                    <%= simple_form_for booking do |f| %>
                      <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
                      <%= f.submit 'Accept', class: 'btn btn-info' %>
                    <% end %>
                    <%= simple_form_for booking do |f| %>
                      <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
                      <%= f.submit 'Reject', class: 'btn btn-info' %>
                    <% end %>
                  <% elsif booking.accepted? %>
                    <%= simple_form_for booking do |f| %>
                      <%= f.input :status, as: :hidden, input_html: { value: 'completed'} %>
                      <%= f.submit 'Complete', class: 'btn btn-info' %>
                    <% end %>
                  <% elsif booking.completed? %>
                    <%= simple_form_for(booking) do |f| %>
                      <%= f.input :photo, as: :file %>
                      <%= f.submit 'Accept', class: 'btn btn-info' %>
                    <% end %>
                  <% else %>
                    <p class="booking-status"><%= booking.status %></p>
                  <% end %>
                </div>
              </div>
            </div>
            <% else %>
            <p>There are no bookings</p>
          <% end %>
        <% end %>
    <% end %>
    <% else %>
    <p>you can also become a prankster!</p>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prankt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="path/to/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Arvo:wght@400&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div style="padding-top:70px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<main class="bg-white">
<div class="logo">
  <%= image_tag "https://res.cloudinary.com/dzwpbkn3u/image/upload/c_scale,w_350/v1621996542/logo_hp9w9n.png", alt: "logo" %>
</div>
  <div class="flexbox-container">
    <%= image_tag "https://res.cloudinary.com/dzwpbkn3u/image/upload/v1622152512/image1194_1_v7chjw.png", alt: "something" %>
      <div class="text-box">
        <div class="intro-para">
          <p class="font-space"><b>Yes, you read it right.</b></br>
            We do pranks, professionally.</br>
        <%= link_to 'See our pranks', pranks_path, class: "btn btn-warning btn-block" %></p>
      </div>
    </div>
  </div>
</main>

app/views/pranks/index.html.erb
<div class="bg-white">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://cdn.dribbble.com/users/3347395/screenshots/8929289/media/6018c0ee5221aaac40add5132baf70ea.png?compress=1&resize=1600x1200);">
    <div class="container">
      <h1>Prankt brings <strong>creative pranks</strong> to <strong>creative people</strong>!</h1>
    </br>
    <p>Search for pranks below, and modify your own!</p>
    <div class="search">
      <%= form_tag pranks_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          id: "search-form",
          placeholder: "What prank do you want to pull?"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
  <h1>All pranks</h1>
</div>
<div class="container-pranks">
    <div class="container-cards pt-3">
      <div class="card-prank">
        <% @pranks.each do |prank| %>
          <div class="card-test">
            <%= prank.photo.attached? ? cl_image_tag(prank.photo.key) : cl_image_tag("https://res.cloudinary.com/dzwpbkn3u/image/upload/v1621747327/homeless-chic_n3ntvs.png") %>
            <div class='ml-3 d-flex flex-column justify-content-between h-100 p-4 '>
             <div class="prank-name"><%= link_to prank.name, prank_path(prank) %></div>
              <div class='d-flex mt-3 justify-content-between'>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</br>
</div>

app/views/pranks/new.html.erb
<div class="container">
  <h1>Add a prank!</h1>
  <%= simple_form_for [@prank] do |f| %>
    <%= f.input :name %>
    <%= f.input :content %>
    <%= f.input :price %>
    <%= f.input :city %>
    <%= f.input :photo, as: :file, inline_label: 'photo', label: false %>
    <%= f.submit 'List your prank!', class: 'btn btn-flat' %>
  <% end %>
</div>

app/views/pranks/show.html.erb
<div class="container-prank">
  <div class="top d-flex flex-column justify-content-center align-items-center">
      <h2 class="text-center"><%= @prank.name %></h2>
    <div class="floating align-items-center ml-5" style="height: 150px; width: 150px;">
    <%= @prank.photo.attached? ? cl_image_tag(@prank.photo.key) : cl_image_tag("https://res.cloudinary.com/dzwpbkn3u/image/upload/v1621747327/homeless-chic_n3ntvs.png") %>
    </div>
  </div>
    <div class="bottom d-flex justify-content-center flex-wrap">
      <div class="info text-center p-3" style="width: 400px">
      <p><strong>Price:</strong></br><%= @prank.price %> yen</p>
      <p><strong>Location: </strong></br><%= @prank.city %></p>
      <p><strong>Description:</strong></br><%= @prank.content %></p>
    </div>
    <% unless current_user == @prank.user %>
      <div class="form d-flex justify-content-center align-items-center p-3">
    <%= simple_form_for [@prank, @booking] do |f| %>
      <%= f.input :date, html5: true, :input_html => { :value => Date.today} %>
      <%= f.input :description, placeholder: 'special instructions', inline_label: 'description' %>
      <%= f.submit class: 'btn btn-flat mb-3 mt-3', value: "Book" %>
    <% end %>
    <% end %>
</div>

  </div>
    <div class="d-flex justify-content-center mt-5">
      <%= link_to 'Go back', pranks_path, class: 'btn btn-flat mb-3 mt-3' %>
    </div>
  </div>

app/views/shared/_footer.html.erb
  <!-- Site footer -->
<div class="footer">
  <div class="footer-box">
    <div class="footer-icons">
      <a href="#"><i class="fab fa-instagram-square"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-facebook-square"></i></a>
    </div>
    <div class="footer-copyright">
      © 2021 Prankt, Inc.
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dzwpbkn3u/image/upload/v1621996542/logo_hp9w9n.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "List a prank!", new_prank_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Your bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-flat" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>